### PR TITLE
Generate a module name in globalize when shimming an unnamed define (for Almond)

### LINKED ISSUE #29: globalize transform breaks almond when shimming an unnamed define
[Almond expects to work with named defines](https://github.com/jrburke/almond#incorrect-module-build-no-module-name), so when globalize transforms an unnamed define it breaks when it calls to the actual `define` (which is almond's define) (calling through to the actual `define` was introduced in b06bc0c).

### PR DESCRIPTION
**Pull request by nicolasv**
Fixes #29.

### CODE REVIEW

File: test/transform.globalize.js [hunk 1]
```diff
@@ -5,6 +5,8 @@ var mocha = require('mocha');
 var transform = require('../src/transform/globalize');
 
 mocha.describe('transform/globalize', function () {
+  var generatedModuleName = '__1dd241c4cd3fd1dd89c570cee98b79dd';
```
Comment (nicolasv) [inline test/transform.globalize.js]: I'm not sure what part the test data generates this particular module name, but it would be nice to pull that particular string out to this same scope so that the different `mocha.describe(…)` blocks don't go out of sync.

Comment (treshugart) [inline test/transform.globalize.js]: It's a hash of `test.js` which is what is used as the file path in the tests. I believe in master that part is abstracted out.

**Comment by treshugart** [comment]
:+1:
